image: nberlette/gitpod-enhanced:latest

ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: |
      pnpm install --global prisma 
      brew install supabase/tap/supabase

    command: |
      ( 
        RED='\033[0;31m'; BOLD='\033[1;30m'; NC='\033[0m';
        gp env | grep --quiet VITE_SUPABASE_URL
        if [ $? -gt 0 ]; then
          printf "${RED}Missing environment variables for supabase!${NC}\n\n"
          printf "To configure them:\n\n1. ${BOLD}gp env -e VITE_SUPABASE_URL={url} VITE_SUPABASE_ANON_KEY={anon_key}${NC}\n\n2. ${BOLD}gp stop${NC}\n\n3. restart your workspace\n"
        else
          export HMR_HOST=$(gp url 3000) && pnpm run dev; 
        fi
      )

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addBadge: true
    addLabel: true

vscode:
  extensions:
    - svelte.svelte-vscode
    - eamodio.gitlens
    - editorconfig.editorconfig
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
